// src/app/[locale]/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../lib/context/authProvider";
import Header from "../lib/components/default/header";
import Footer from "../lib/components/default/footer";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { getTranslations } from "next-intl/server";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(props: {
    children: React.ReactNode;
    params: { locale: string } | Promise<{ locale: string }>; // <- notice Promise
}) {
    // Await params if it's a Promise
    const { locale } = await props.params;
    const messages = await getMessages({ locale });

    return (
        <AuthProvider>
            <html lang={locale}>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                        <Header messages={messages} />
                        <div></div>
                        {props.children}
                        <Footer />
                    </NextIntlClientProvider>
                </body>
            </html>
        </AuthProvider>
    );
}
