import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./lib/context/authProvider";
import Header from "./lib/components/default/header";
import Footer from "./lib/components/default/footer";
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    // params: { locale }
}: Readonly<{
    children: React.ReactNode;
    // params: { locale: string };
}>) {

    return (
        <AuthProvider>
            <html lang="de">
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    {/* <NextIntlClientProvider locale={locale} messages={messages}> */}
                        <Header />
                        {children}
                        <Footer />
                    {/* </NextIntlClientProvider> */}
                </body>
            </html>
        </AuthProvider>
    );
}
